Repository smithy-lang/smithy-rs, pull requests merged in 2022-06, with the labels that each got.

#1424 Comply with content types for the accept header
  codegen-server/src/main/kotlin/software/amazon/smithy/rust/codegen/server/smithy/generators/protocol/ServerProtocolTestGenerator.kt
  codegen-server/src/main/kotlin/software/amazon/smithy/rust/codegen/server/smithy/protocols/ServerHttpBoundProtocolGenerator.kt
  codegen/src/main/kotlin/software/amazon/smithy/rust/codegen/smithy/protocols/RestJson.kt
  rust-runtime/aws-smithy-http-server/src/runtime_error.rs
Labels: needs-sdk-review

#1449 Docker hop limit
  CHANGELOG.next.toml
  aws/rust-runtime/aws-config/src/imds/client.rs
Labels: waiting-on-author

#1507 Fix simple model error
  codegen-server-test/model/simple.smithy
Labels: server

#1423 Set Content-Length header in server responses
  codegen-server-test/model/simple.smithy
  codegen-server/src/main/kotlin/software/amazon/smithy/rust/codegen/server/smithy/protocols/ServerHttpBoundProtocolGenerator.kt
  codegen-test/model/misc.smithy
Labels: needs-sdk-review

#1466 Add getter methods to OperationExtension
  rust-runtime/aws-smithy-http-server/src/extension.rs
Labels: needs-sdk-review
