Repository smithy-lang/smithy-rs, pull requests merged in 2023-11, with the labels that each got.

#3123 Grant the lambda execution role access to the MRAP bucket
  tools/ci-cdk/lib/aws-sdk-rust/canary-stack.ts
Labels: needs-backport

#3120 Fix smithy types docs
  .github/workflows/pull-request-bot.yml
  rust-runtime/aws-smithy-types/src/byte_stream.rs
  rust-runtime/aws-smithy-types/src/lib.rs
  tools/ci-scripts/check-only-aws-sdk-services
  tools/ci-scripts/check-rust-runtimes
Labels: needs-backport

#3126 Fix aws-sdk-rust#930 (PutSnapshotBlock)
  CHANGELOG.next.toml
  aws/sdk-codegen/src/main/kotlin/software/amazon/smithy/rustsdk/SigV4AuthDecorator.kt
  aws/sdk-codegen/src/test/kotlin/software/amazon/smithy/rustsdk/SigV4AuthDecoratorTest.kt
Labels: needs-sdk-review, needs-backport

#3139 Move `Message`, `Header`, `HeaderValue`, and `StrBytes` from `aws-smithy-eventstream` to `aws-smithy-types`
  CHANGELOG.next.toml
  aws/rust-runtime/aws-runtime/src/auth/sigv4.rs
  aws/rust-runtime/aws-sigv4/Cargo.toml
  aws/rust-runtime/aws-sigv4/external-types.toml
  aws/rust-runtime/aws-sigv4/src/event_stream.rs
  aws/sdk/integration-tests/transcribestreaming/tests/test.rs
  codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/ClientRustModule.kt
  codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/customize/RequiredCustomizations.kt
  codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/generators/ClientEnumGenerator.kt
  codegen-core/src/main/kotlin/software/amazon/smithy/rust/codegen/core/smithy/customizations/SmithyTypesPubUseExtra.kt
  codegen-core/src/main/kotlin/software/amazon/smithy/rust/codegen/core/smithy/protocols/parse/EventStreamUnmarshallerGenerator.kt
  codegen-core/src/main/kotlin/software/amazon/smithy/rust/codegen/core/smithy/protocols/serialize/EventStreamErrorMarshallerGenerator.kt
  codegen-core/src/main/kotlin/software/amazon/smithy/rust/codegen/core/smithy/protocols/serialize/EventStreamMarshallerGenerator.kt
  codegen-core/src/main/kotlin/software/amazon/smithy/rust/codegen/core/testutil/EventStreamMarshallTestCases.kt
  codegen-core/src/main/kotlin/software/amazon/smithy/rust/codegen/core/testutil/EventStreamUnmarshallTestCases.kt
  rust-runtime/aws-smithy-eventstream/fuzz/fuzz_targets/corrected_prelude_crc.rs
  rust-runtime/aws-smithy-eventstream/fuzz/fuzz_targets/mutated_headers.rs
  rust-runtime/aws-smithy-eventstream/fuzz/fuzz_targets/prelude.rs
  rust-runtime/aws-smithy-eventstream/fuzz/fuzz_targets/raw_bytes.rs
  rust-runtime/aws-smithy-eventstream/fuzz/fuzz_targets/round_trip.rs
  rust-runtime/aws-smithy-eventstream/src/arbitrary.rs
  rust-runtime/aws-smithy-eventstream/src/error.rs
  rust-runtime/aws-smithy-eventstream/src/frame.rs
  rust-runtime/aws-smithy-eventstream/src/lib.rs
  rust-runtime/aws-smithy-eventstream/src/smithy.rs
  rust-runtime/aws-smithy-http/src/event_stream/receiver.rs
  rust-runtime/aws-smithy-http/src/event_stream/sender.rs
  rust-runtime/aws-smithy-types/src/event_stream.rs
  rust-runtime/aws-smithy-types/src/lib.rs
  rust-runtime/aws-smithy-types/src/str_bytes.rs
Labels: breaking-change, needs-sdk-review, needs-server-review

#3114 Avoid exposing `aws_smithy_http::event_stream::receiver::Receiver` in SDK's public API
  CHANGELOG.next.toml
  codegen-client/src/test/kotlin/software/amazon/smithy/rust/codegen/client/smithy/EventStreamSymbolProviderTest.kt
  codegen-core/src/main/kotlin/software/amazon/smithy/rust/codegen/core/rustlang/CargoDependency.kt
  codegen-core/src/main/kotlin/software/amazon/smithy/rust/codegen/core/smithy/EventStreamSymbolProvider.kt
  codegen-core/src/main/kotlin/software/amazon/smithy/rust/codegen/core/smithy/RuntimeType.kt
  codegen-core/src/main/kotlin/software/amazon/smithy/rust/codegen/core/smithy/generators/http/HttpBindingGenerator.kt
  rust-runtime/aws-smithy-http/src/event_stream.rs
  rust-runtime/aws-smithy-http/src/event_stream/receiver.rs
  rust-runtime/aws-smithy-types/src/event_stream.rs
  rust-runtime/inlineable/Cargo.toml
  rust-runtime/inlineable/src/event_receiver.rs
  rust-runtime/inlineable/src/lib.rs
  tools/ci-cdk/canary-runner/src/build_bundle.rs
Labels: breaking-change, needs-sdk-review

#3082 Update release tooling to handle both stable and unstable crates
  .github/workflows/release.yml
  aws/rust-runtime/aws-config/Cargo.toml
  aws/rust-runtime/aws-runtime-api/Cargo.toml
  aws/rust-runtime/aws-types/Cargo.toml
  aws/rust-runtime/aws-types/src/build_metadata.rs
  aws/sdk-codegen/build.gradle.kts
  aws/sdk/build.gradle.kts
  buildSrc/src/main/kotlin/CrateSet.kt
  buildSrc/src/main/kotlin/ManifestPatcher.kt
  buildSrc/src/main/kotlin/aws/sdk/CrateVersioner.kt
  buildSrc/src/main/kotlin/aws/sdk/ServiceLoader.kt
  buildSrc/src/test/kotlin/CrateSetTest.kt
  gradle.properties
  rust-runtime/aws-smithy-async/Cargo.toml
  rust-runtime/aws-smithy-runtime-api/Cargo.toml
  rust-runtime/aws-smithy-types/Cargo.toml
  rust-runtime/build.gradle.kts
  tools/ci-build/publisher/Cargo.lock
  tools/ci-build/publisher/Cargo.toml
  tools/ci-build/publisher/src/publish.rs
  tools/ci-build/publisher/src/subcommand/fix_manifests.rs
  tools/ci-build/publisher/src/subcommand/fix_manifests/validate.rs
  tools/ci-build/publisher/src/subcommand/upgrade_runtime_crates_version.rs
  tools/ci-build/smithy-rs-tool-common/src/package.rs
  tools/ci-scripts/upgrade-gradle-properties
Labels: needs-server-review

#3153 Update crate guidance to match top-level guidance
  aws/sdk-codegen/src/main/kotlin/software/amazon/smithy/rustsdk/AwsCrateDocsDecorator.kt
Labels: needs-backport

#3159 Add benchmark that compares current with previous release
  aws/sdk/benchmarks/previous-release-comparison/Cargo.lock
  aws/sdk/benchmarks/previous-release-comparison/Cargo.toml
  aws/sdk/benchmarks/previous-release-comparison/benches/README.md
  aws/sdk/benchmarks/previous-release-comparison/benches/previous_release_comparison.rs
Labels: needs-sdk-review

#3173 Clean up re-exports and improve 'BuildError' conversions
  CHANGELOG.next.toml
  aws/sdk-codegen/src/main/kotlin/software/amazon/smithy/rustsdk/AwsFluentClientDecorator.kt
  aws/sdk-codegen/src/main/kotlin/software/amazon/smithy/rustsdk/CredentialProviders.kt
  aws/sdk-codegen/src/main/kotlin/software/amazon/smithy/rustsdk/RegionDecorator.kt
  aws/sdk/integration-tests/dynamodb/tests/build-errors.rs
  codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/ClientReExports.kt
  codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/customizations/HttpAuthDecorator.kt
  codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/customizations/HttpConnectorConfigDecorator.kt
  codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/customizations/IdentityCacheDecorator.kt
  codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/customizations/InterceptorConfigCustomization.kt
  codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/customizations/ResiliencyConfigCustomization.kt
  codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/customize/RequiredCustomizations.kt
  codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/endpoint/EndpointConfigCustomization.kt
  codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/generators/ClientRuntimeTypesReExportGenerator.kt
  codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/generators/config/ServiceConfigGenerator.kt
  codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/generators/error/ServiceErrorGenerator.kt
  rust-runtime/aws-smithy-runtime-api/src/client/result.rs
Labels: needs-backport

#3179 Remove cargo doc from all-services check to speed up CI
  tools/ci-scripts/check-aws-sdk-smoketest-docs-clippy-udeps
  tools/ci-scripts/check-only-aws-sdk-services
Labels: needs-sdk-review, needs-backport

#3157 Fix panics in `Headers::try_insert` and `Headers::try_append`
  rust-runtime/aws-smithy-runtime-api/Cargo.toml
  rust-runtime/aws-smithy-runtime-api/src/http/headers.rs
Labels: needs-sdk-review

#3160 Move `RequestId` to aws-types
  CHANGELOG.next.toml
  aws/rust-runtime/aws-http/Cargo.toml
  aws/rust-runtime/aws-http/src/lib.rs
  aws/rust-runtime/aws-inlineable/src/s3_request_id.rs
  aws/rust-runtime/aws-types/external-types.toml
  aws/rust-runtime/aws-types/src/lib.rs
  aws/rust-runtime/aws-types/src/request_id.rs
  aws/sdk-codegen/src/main/kotlin/software/amazon/smithy/rustsdk/AwsRequestIdDecorator.kt
  rust-runtime/aws-smithy-http/src/http.rs
  rust-runtime/aws-smithy-http/src/lib.rs
Labels: breaking-change, needs-sdk-review

#3175 Fix compilation error in generate code caused by name collision
  codegen-client/src/test/kotlin/software/amazon/smithy/rust/codegen/client/smithy/NamingObstacleCourseTest.kt
  codegen-core/src/main/kotlin/software/amazon/smithy/rust/codegen/core/smithy/protocols/ProtocolFunctions.kt
  codegen-core/src/main/kotlin/software/amazon/smithy/rust/codegen/core/testutil/NamingObstacleCourseTestModels.kt
Labels: needs-sdk-review, needs-backport

#3198 Re-introduce default generic for server service struct
  codegen-server/src/main/kotlin/software/amazon/smithy/rust/codegen/server/smithy/generators/ServerServiceGenerator.kt
  codegen-server/src/test/kotlin/software/amazon/smithy/rust/codegen/server/smithy/generators/ServerServiceGeneratorTest.kt
Labels: server

#3197 Re-introduce default generic for server service struct
  codegen-server/src/main/kotlin/software/amazon/smithy/rust/codegen/server/smithy/generators/ServerServiceGenerator.kt
  codegen-server/src/test/kotlin/software/amazon/smithy/rust/codegen/server/smithy/generators/ServerServiceGeneratorTest.kt
Labels: bug, server, needs-backport

#3189 Implement ProvideErrorMetadata for service errors
  CHANGELOG.next.toml
  codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/customize/RequiredCustomizations.kt
  codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/generators/error/OperationErrorGenerator.kt
  codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/generators/error/ServiceErrorGenerator.kt
  codegen-client/src/test/kotlin/software/amazon/smithy/rust/codegen/client/smithy/generators/error/ServiceErrorGeneratorTest.kt
Labels: breaking-change

#3196 Remove `CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse` in CI
  tools/ci-build/Dockerfile
Labels: needs-server-review

#3192 Rely on `.cargo/config.toml` instead of `RUSTFLAGS` in tests' generated crates
  codegen-client/src/test/kotlin/software/amazon/smithy/rust/codegen/client/smithy/endpoint/EndpointResolverGeneratorTest.kt
  codegen-client/src/test/kotlin/software/amazon/smithy/rust/codegen/client/smithy/endpoint/EndpointsDecoratorTest.kt
  codegen-core/src/main/kotlin/software/amazon/smithy/rust/codegen/core/testutil/CodegenIntegrationTest.kt
  codegen-core/src/main/kotlin/software/amazon/smithy/rust/codegen/core/testutil/Rust.kt
Labels: needs-server-review

#3201 Enable stable & unstable versions in release workflow
  .github/workflows/release.yml
  tools/ci-build/publisher/src/subcommand/fix_manifests.rs
  tools/ci-scripts/upgrade-gradle-properties
Labels: needs-sdk-review

#3191 Revise unhandled error variant according to RFC-39
  CHANGELOG.next.toml
  aws/rust-runtime/aws-inlineable/src/s3_request_id.rs
  aws/rust-runtime/aws-types/src/request_id.rs
  aws/sdk-codegen/src/main/kotlin/software/amazon/smithy/rustsdk/BaseRequestIdDecorator.kt
  aws/sdk/integration-tests/lambda/tests/request_id.rs
  aws/sdk/integration-tests/s3/tests/query-strings-are-correctly-encoded.rs
  aws/sdk/integration-tests/s3/tests/request_id.rs
  codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/generators/ClientEnumGenerator.kt
  codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/generators/error/OperationErrorGenerator.kt
  codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/generators/error/ServiceErrorGenerator.kt
  codegen-client/src/test/kotlin/software/amazon/smithy/rust/codegen/client/smithy/generators/ClientEnumGeneratorTest.kt
  codegen-client/src/test/kotlin/software/amazon/smithy/rust/codegen/client/smithy/protocols/eventstream/ClientEventStreamUnmarshallerGeneratorTest.kt
  codegen-core/src/main/kotlin/software/amazon/smithy/rust/codegen/core/smithy/RuntimeType.kt
  examples/pokemon-service-client-usage/examples/handling-errors.rs
  rust-runtime/aws-smithy-runtime-api/external-types.toml
  rust-runtime/aws-smithy-runtime-api/src/http.rs
  rust-runtime/aws-smithy-types/src/error.rs
  rust-runtime/aws-smithy-types/src/error/unhandled.rs
Labels: breaking-change

#3204 Rename behavior versions and associated functions
  CHANGELOG.next.toml
  aws/rust-runtime/aws-config/external-types.toml
  aws/rust-runtime/aws-config/src/default_provider/app_name.rs
  aws/rust-runtime/aws-config/src/lib.rs
  aws/rust-runtime/aws-config/src/provider_config.rs
  aws/rust-runtime/aws-config/src/sso/token.rs
  aws/rust-runtime/aws-config/src/sts/assume_role.rs
  aws/rust-runtime/aws-types/external-types.toml
  aws/rust-runtime/aws-types/src/sdk_config.rs
  aws/sdk-codegen/src/main/kotlin/software/amazon/smithy/rustsdk/AwsFluentClientDecorator.kt
  aws/sdk-codegen/src/main/kotlin/software/amazon/smithy/rustsdk/SdkConfigDecorator.kt
  aws/sdk/integration-tests/no-default-features/tests/client-construction.rs
  aws/sdk/integration-tests/s3/tests/endpoints.rs
  codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/generators/client/FluentClientGenerator.kt
  codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/generators/config/ServiceConfigGenerator.kt
  design/src/SUMMARY.md
  design/src/rfcs/overview.md
  design/src/rfcs/rfc0040_behavior_versions.md
  rust-runtime/aws-smithy-runtime-api/src/client/behavior_version.rs
  rust-runtime/aws-smithy-runtime/src/client/defaults.rs
Labels: breaking-change, needs-sdk-review

#3207 Add a job to release workflow that checks the current actor for prod run
  .github/workflows/release.yml
Labels: needs-server-review

#3216 Merge 0.100.x back into main
  buildSrc/src/main/kotlin/CodegenTestCommon.kt
  codegen-client-test/build.gradle.kts
  codegen-core/common-test-models/aws-json-query-compat.smithy
  codegen-core/src/main/kotlin/software/amazon/smithy/rust/codegen/core/smithy/protocols/AwsQueryCompatible.kt
Labels: needs-sdk-review

#3219 Only output dev preview warning messages for 0.x versions
  aws/SDK_README.md.hb
  aws/rust-runtime/aws-config/README.md
  aws/sdk-codegen/src/main/kotlin/software/amazon/smithy/rustsdk/AwsCrateDocsDecorator.kt
  aws/sdk-codegen/src/test/kotlin/AwsCrateDocsDecoratorTest.kt
  aws/sdk-codegen/src/test/kotlin/SdkCodegenIntegrationTest.kt
  aws/sdk-codegen/src/test/kotlin/software/amazon/smithy/rustsdk/TestUtil.kt
  codegen-core/src/main/kotlin/software/amazon/smithy/rust/codegen/core/testutil/CodegenIntegrationTest.kt
  codegen-core/src/main/kotlin/software/amazon/smithy/rust/codegen/core/testutil/Rust.kt
  tools/ci-build/publisher/src/subcommand/hydrate_readme.rs
Labels: needs-sdk-review

#3231 Remove `supports_v2023_11_09` from behavior versions
  rust-runtime/aws-smithy-runtime-api/src/client/behavior_version.rs
Labels: breaking-change

#3222 Remove deprecations from rust-runtime
  CHANGELOG.next.toml
  aws/rust-runtime/aws-config/src/environment/app_name.rs
  aws/rust-runtime/aws-config/src/environment/mod.rs
  aws/rust-runtime/aws-config/src/lib.rs
  aws/rust-runtime/aws-config/src/profile/app_name.rs
  aws/rust-runtime/aws-config/src/profile/mod.rs
  aws/rust-runtime/aws-config/src/provider_config.rs
  aws/rust-runtime/aws-inlineable/src/s3_request_id.rs
  aws/rust-runtime/aws-runtime/src/retries/classifiers.rs
  aws/rust-runtime/aws-types/src/config.rs
  aws/rust-runtime/aws-types/src/request_id.rs
  aws/sdk/integration-tests/dynamodb/benches/deserialization_bench.rs
  aws/sdk/integration-tests/dynamodb/benches/serialization_bench.rs
  codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/customizations/HttpConnectorConfigDecorator.kt
  codegen-client/src/test/kotlin/software/amazon/smithy/rust/codegen/client/smithy/customizations/HttpAuthDecoratorTest.kt
  codegen-client/src/test/kotlin/software/amazon/smithy/rust/codegen/client/smithy/generators/error/OperationErrorGeneratorTest.kt
  codegen-server/python/src/main/kotlin/software/amazon/smithy/rust/codegen/server/python/smithy/generators/PythonServerEventStreamWrapperGenerator.kt
  rust-runtime/aws-smithy-http/src/body.rs
  rust-runtime/aws-smithy-http/src/byte_stream.rs
  rust-runtime/aws-smithy-http/src/connection.rs
  rust-runtime/aws-smithy-http/src/event_stream/sender.rs
  rust-runtime/aws-smithy-http/src/lib.rs
  rust-runtime/aws-smithy-http/src/operation.rs
  rust-runtime/aws-smithy-http/src/result.rs
  rust-runtime/aws-smithy-runtime-api/src/client/auth.rs
  rust-runtime/aws-smithy-runtime-api/src/client/endpoint.rs
  rust-runtime/aws-smithy-runtime-api/src/client/http.rs
  rust-runtime/aws-smithy-runtime-api/src/client/identity.rs
  rust-runtime/aws-smithy-runtime-api/src/client/interceptors.rs
  rust-runtime/aws-smithy-runtime-api/src/client/result.rs
  rust-runtime/aws-smithy-runtime-api/src/client/ser_de.rs
  rust-runtime/aws-smithy-runtime/src/client/identity/cache.rs
  rust-runtime/aws-smithy-runtime/src/client/identity/cache/lazy.rs
  rust-runtime/aws-smithy-types/src/byte_stream.rs
  rust-runtime/aws-smithy-types/src/error.rs
  rust-runtime/aws-smithy-types/src/error/metadata.rs
  rust-runtime/aws-smithy-types/src/error/unhandled.rs
  rust-runtime/aws-smithy-types/src/lib.rs
  rust-runtime/inlineable/src/json_errors.rs
Labels: breaking-change

#3237 Merge smithy-rs-release-1.x.y back into main
  CHANGELOG.md
  CHANGELOG.next.toml
  aws/SDK_CHANGELOG.next.json
  gradle.properties
Labels: needs-sdk-review

#3245 Clean up remaining `TODO(GA)` from PR#3082
  gradle.properties
  tools/ci-build/publisher/src/subcommand/upgrade_runtime_crates_version.rs
Labels: needs-sdk-review, needs-backport

#3241 Disable dev preview for `CrateVersioner`
  buildSrc/src/main/kotlin/aws/sdk/CrateVersioner.kt
Labels: needs-sdk-review, needs-backport

#3248 Merge smithy-rs-release-1.x.y back into main
  CHANGELOG.md
  aws/SDK_CHANGELOG.next.json
  aws/sdk-codegen/src/main/kotlin/software/amazon/smithy/rustsdk/customize/RemoveDefaultsDecorator.kt
  buildSrc/src/main/kotlin/aws/sdk/CrateVersioner.kt
  gradle.properties
  rust-runtime/aws-smithy-runtime/Cargo.toml
  rust-runtime/aws-smithy-runtime/src/client/http/body/minimum_throughput.rs
  rust-runtime/aws-smithy-runtime/src/client/http/body/minimum_throughput/http_body_0_4_x.rs
  rust-runtime/aws-smithy-runtime/src/client/http/body/minimum_throughput/options.rs
  rust-runtime/aws-smithy-runtime/src/client/http/body/minimum_throughput/throughput.rs
  rust-runtime/aws-smithy-runtime/tests/stalled_stream_performance.rs
  tools/ci-build/publisher/src/subcommand/upgrade_runtime_crates_version.rs
Labels: needs-sdk-review

#3259 Stop tagging releases as prereleases
  .github/workflows/release.yml
  tools/ci-build/changelogger/src/render.rs
  tools/ci-build/changelogger/tests/e2e_test.rs
Labels: needs-sdk-review

#3261 Add suffix support to release tags in tooling
  tools/ci-build/smithy-rs-tool-common/src/release_tag.rs
Labels: needs-sdk-review

#3272 Fix running semver-checks on `aws-config`
  tools/ci-scripts/codegen-diff/diff_lib.py
  tools/ci-scripts/codegen-diff/semver-checks.py
Labels: needs-sdk-review

#3269 Improve client init time by switching to regex-lite
  CHANGELOG.next.toml
  aws/rust-runtime/aws-sigv4/Cargo.toml
  aws/rust-runtime/aws-sigv4/src/http_request/canonical_request.rs
  aws/rust-runtime/aws-sigv4/src/http_request/error.rs
  codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/endpoint/Util.kt
  codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/endpoint/generators/EndpointResolverGenerator.kt
  codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/endpoint/rulesgen/StdLib.kt
  codegen-core/src/main/kotlin/software/amazon/smithy/rust/codegen/core/rustlang/CargoDependency.kt
  codegen-core/src/main/kotlin/software/amazon/smithy/rust/codegen/core/smithy/RuntimeType.kt
  rust-runtime/aws-smithy-protocol-test/Cargo.toml
  rust-runtime/aws-smithy-protocol-test/src/urlencoded.rs
  rust-runtime/inlineable/Cargo.toml
  rust-runtime/inlineable/src/endpoint_lib/partition.rs
  rust-runtime/inlineable/src/endpoint_lib/s3.rs
  rust-runtime/inlineable/src/lib.rs
Labels: needs-sdk-review

#3262 Lazy initialize the default HTTP client
  CHANGELOG.next.toml
  aws/sdk/integration-tests/s3/tests/service_timeout_overrides.rs
  rust-runtime/aws-smithy-runtime-api/rustdoc/validate_base_client_config.md
  rust-runtime/aws-smithy-runtime-api/rustdoc/validate_final_config.md
  rust-runtime/aws-smithy-runtime-api/src/client/http.rs
  rust-runtime/aws-smithy-runtime-api/src/client/identity.rs
  rust-runtime/aws-smithy-runtime-api/src/client/runtime_components.rs
  rust-runtime/aws-smithy-runtime/src/client/http/hyper_014.rs
  rust-runtime/aws-smithy-runtime/src/client/http/test_util/never.rs
Labels: needs-sdk-review
