Repository smithy-lang/smithy-rs, pull requests merged in 2024-02, with the labels that each got.

#3395 Fix rustdoc CI
  .github/workflows/pull-request-bot.yml
Labels: needs-sdk-review

#3399 Fix clap MSRV issue
  aws/rust-runtime/aws-sigv4/Cargo.toml
  aws/sdk-codegen/src/main/kotlin/software/amazon/smithy/rustsdk/IntegrationTestDependencies.kt
  aws/sdk/integration-tests/dynamodb/Cargo.toml
  examples/pokemon-service/Cargo.toml
  rust-runtime/aws-smithy-types/Cargo.toml
Labels: needs-sdk-review

#3397 Upgrade Smithy to 1.44
  codegen-core/common-test-models/rest-json-extras.smithy
  codegen-server/src/main/kotlin/software/amazon/smithy/rust/codegen/server/smithy/generators/protocol/ServerProtocolTestGenerator.kt
  gradle.properties
  rust-runtime/aws-smithy-types/src/blob.rs
Labels: needs-sdk-review

#3383 Add CI step to release workflow to check for semver hazards
  .github/workflows/release.yml
  tools/ci-scripts/check-semver-hazards
Labels: needs-sdk-review

#3402 Cap the max jitter fraction for cache refresh buffer time to 0.5
  CHANGELOG.next.toml
  rust-runtime/aws-smithy-runtime/src/client/identity/cache/lazy.rs
Labels: needs-sdk-review

#3386 Add placeholder types for S3 Express and enable control flow to be redirected for S3 Express use case
  .github/workflows/release.yml
  CHANGELOG.md
  CHANGELOG.next.toml
  aws/SDK_CHANGELOG.next.json
  aws/rust-runtime/aws-inlineable/src/lib.rs
  aws/rust-runtime/aws-inlineable/src/s3_express.rs
  aws/rust-runtime/aws-runtime/src/retries/classifiers.rs
  aws/rust-runtime/aws-sigv4/Cargo.toml
  aws/sdk-codegen/src/main/kotlin/software/amazon/smithy/rustsdk/AwsCodegenDecorator.kt
  aws/sdk-codegen/src/main/kotlin/software/amazon/smithy/rustsdk/IntegrationTestDependencies.kt
  aws/sdk-codegen/src/main/kotlin/software/amazon/smithy/rustsdk/customize/s3/S3ExpressDecorator.kt
  aws/sdk-codegen/src/main/kotlin/software/amazon/smithy/rustsdk/endpoints/OperationInputTestGenerator.kt
  aws/sdk/integration-tests/Cargo.toml
  aws/sdk/integration-tests/dynamodb/Cargo.toml
  aws/sdk/integration-tests/s3/tests/retry-classifier-customization.rs
  codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/generators/ServiceRuntimePluginGenerator.kt
  codegen-core/common-test-models/rest-json-extras.smithy
  codegen-server/src/main/kotlin/software/amazon/smithy/rust/codegen/server/smithy/generators/protocol/ServerProtocolTestGenerator.kt
  examples/pokemon-service/Cargo.toml
  gradle.properties
  rust-runtime/aws-smithy-runtime-api/src/client/identity.rs
  rust-runtime/aws-smithy-runtime-api/src/client/retries/classifiers.rs
  rust-runtime/aws-smithy-runtime-api/src/client/runtime_components.rs
  rust-runtime/aws-smithy-runtime/src/client/identity/cache/lazy.rs
  rust-runtime/aws-smithy-runtime/src/client/orchestrator/auth.rs
  rust-runtime/aws-smithy-types/Cargo.toml
  rust-runtime/aws-smithy-types/src/blob.rs
  tools/ci-scripts/check-semver-hazards
Labels: needs-sdk-review

#3387 Only create inner chain provider once in profile creds provider
  CHANGELOG.next.toml
  aws/rust-runtime/aws-config/src/profile/credentials.rs
  aws/rust-runtime/aws-config/src/profile/mod.rs
  aws/rust-runtime/aws-credential-types/src/provider.rs
Labels: needs-sdk-review

#3388 Allow list-objects-v2 to run against an S3 Express bucket
  aws/rust-runtime/aws-inlineable/src/s3_express.rs
  aws/rust-runtime/aws-runtime/src/auth/sigv4.rs
  aws/rust-runtime/aws-sigv4/src/http_request/canonical_request.rs
  aws/rust-runtime/aws-sigv4/src/http_request/settings.rs
  aws/rust-runtime/aws-sigv4/src/http_request/sign.rs
  aws/sdk-codegen/src/main/kotlin/software/amazon/smithy/rustsdk/EndpointBuiltInsDecorator.kt
  aws/sdk-codegen/src/main/kotlin/software/amazon/smithy/rustsdk/RegionDecorator.kt
  aws/sdk-codegen/src/main/kotlin/software/amazon/smithy/rustsdk/UserAgentDecorator.kt
  aws/sdk-codegen/src/main/kotlin/software/amazon/smithy/rustsdk/customize/s3/S3Decorator.kt
  aws/sdk-codegen/src/main/kotlin/software/amazon/smithy/rustsdk/endpoints/OperationInputTestGenerator.kt
  aws/sdk/integration-tests/s3/tests/data/express/list-objects-v2.json
  aws/sdk/integration-tests/s3/tests/express.rs
  codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/customizations/ResiliencyConfigCustomization.kt
  codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/endpoint/ClientContextConfigCustomization.kt
  codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/generators/config/ServiceConfigGenerator.kt
  codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/generators/config/StalledStreamProtectionConfigCustomization.kt
  codegen-client/src/test/kotlin/software/amazon/smithy/rust/codegen/client/smithy/generators/config/ServiceConfigGeneratorTest.kt
  rust-runtime/aws-smithy-runtime-api/src/client/runtime_components.rs
Labels: needs-sdk-review

#3425 Fix credentials-verification workflow
  .github/workflows/credentials-verification.yml
Labels: needs-sdk-review

#3390 Add S3 Express identity cache
  aws/rust-runtime/aws-inlineable/Cargo.toml
  aws/rust-runtime/aws-inlineable/src/s3_express.rs
  aws/sdk-codegen/src/main/kotlin/software/amazon/smithy/rustsdk/customize/s3/S3ExpressDecorator.kt
  aws/sdk/integration-tests/s3/tests/data/express/mixed-auths.json
  aws/sdk/integration-tests/s3/tests/express.rs
  codegen-core/src/main/kotlin/software/amazon/smithy/rust/codegen/core/rustlang/CargoDependency.kt
Labels: needs-sdk-review

#3413 Upgrade cargo-check-external-types to 0.1.11
  .github/workflows/pull-request-bot.yml
  rust-runtime/aws-smithy-async/src/test_util.rs
  rust-runtime/aws-smithy-checksums/Cargo.toml
  rust-runtime/aws-smithy-http-server/src/macros.rs
  rust-runtime/aws-smithy-runtime-api/src/shared.rs
  rust-runtime/aws-smithy-runtime/src/test_util/capture_test_logs.rs
  rust-runtime/aws-smithy-types/src/type_erasure.rs
  tools/ci-build/Dockerfile
Labels: needs-server-review

#3432 Allow S3 Express to use CRC32 for default request checksum
  aws/rust-runtime/aws-inlineable/src/http_request_checksum.rs
  aws/sdk-codegen/src/main/kotlin/software/amazon/smithy/rustsdk/HttpRequestChecksumDecorator.kt
  aws/sdk-codegen/src/main/kotlin/software/amazon/smithy/rustsdk/customize/s3/S3ExpressDecorator.kt
  aws/sdk/integration-tests/s3/tests/express.rs
Labels: needs-sdk-review

#3433 Add support to disable S3 Express session auth
  aws/rust-runtime/aws-inlineable/src/s3_express.rs
  aws/sdk-codegen/src/main/kotlin/software/amazon/smithy/rustsdk/AwsFluentClientDecorator.kt
  aws/sdk-codegen/src/main/kotlin/software/amazon/smithy/rustsdk/customize/s3/S3ExpressDecorator.kt
  aws/sdk/integration-tests/s3/tests/express.rs
  codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/generators/client/FluentClientDecorator.kt
  codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/generators/client/FluentClientGenerator.kt
Labels: needs-sdk-review

#2012 Add CHANGELOG support for multiple reference authors
  tools/ci-build/changelogger/src/render.rs
  tools/ci-build/smithy-rs-tool-common/src/changelog.rs
Labels: ops

#3449 Update authors on WASM changes in changelog
  CHANGELOG.next.toml
Labels: needs-sdk-review

#3442 Implement the default token provider chain
  aws/rust-runtime/aws-config/external-types.toml
  aws/rust-runtime/aws-config/src/default_provider.rs
  aws/rust-runtime/aws-config/src/default_provider/credentials.rs
  aws/rust-runtime/aws-config/src/default_provider/token.rs
  aws/rust-runtime/aws-config/src/lib.rs
  aws/rust-runtime/aws-config/src/meta/mod.rs
  aws/rust-runtime/aws-config/src/meta/token.rs
  aws/rust-runtime/aws-config/src/profile/credentials.rs
  aws/rust-runtime/aws-config/src/profile/credentials/repr.rs
  aws/rust-runtime/aws-config/src/profile/mod.rs
  aws/rust-runtime/aws-config/src/profile/token.rs
  aws/rust-runtime/aws-config/src/sso/token.rs
  aws/rust-runtime/aws-config/src/test_case.rs
  aws/rust-runtime/aws-config/test-data/default-token-provider-chain/profile_keys/env.json
  aws/rust-runtime/aws-config/test-data/default-token-provider-chain/profile_keys/fs/home/.aws/config
  aws/rust-runtime/aws-config/test-data/default-token-provider-chain/profile_keys/fs/home/.aws/sso/cache/d12208e38164f558a1d06c99432ab77dbb346c45.json
  aws/rust-runtime/aws-config/test-data/default-token-provider-chain/profile_keys/http-traffic.json
  aws/rust-runtime/aws-config/test-data/default-token-provider-chain/profile_keys/test-case.json
  aws/rust-runtime/aws-config/test-data/default-token-provider-chain/profile_keys_case_insensitive/env.json
  aws/rust-runtime/aws-config/test-data/default-token-provider-chain/profile_keys_case_insensitive/fs/home/.aws/config
  aws/rust-runtime/aws-config/test-data/default-token-provider-chain/profile_keys_case_insensitive/fs/home/.aws/sso/cache/d12208e38164f558a1d06c99432ab77dbb346c45.json
  aws/rust-runtime/aws-config/test-data/default-token-provider-chain/profile_keys_case_insensitive/http-traffic.json
  aws/rust-runtime/aws-config/test-data/default-token-provider-chain/profile_keys_case_insensitive/test-case.json
  aws/rust-runtime/aws-config/test-data/default-token-provider-chain/profile_name/env.json
  aws/rust-runtime/aws-config/test-data/default-token-provider-chain/profile_name/fs/home/.aws/config
  aws/rust-runtime/aws-config/test-data/default-token-provider-chain/profile_name/fs/home/.aws/sso/cache/29faa2f70ab0f58f60e284d585d95865572f5cbd.json
  aws/rust-runtime/aws-config/test-data/default-token-provider-chain/profile_name/http-traffic.json
  aws/rust-runtime/aws-config/test-data/default-token-provider-chain/profile_name/test-case.json
  aws/rust-runtime/aws-credential-types/Cargo.toml
  aws/rust-runtime/aws-credential-types/external-types.toml
  aws/rust-runtime/aws-credential-types/src/lib.rs
  aws/rust-runtime/aws-credential-types/src/provider/error.rs
  aws/rust-runtime/aws-credential-types/src/provider/future.rs
  aws/rust-runtime/aws-credential-types/src/provider/token.rs
  aws/rust-runtime/aws-credential-types/src/token_fn.rs
  aws/rust-runtime/aws-credential-types/src/token_impl.rs
  aws/rust-runtime/aws-types/external-types.toml
  aws/rust-runtime/aws-types/src/sdk_config.rs
  rust-runtime/aws-smithy-runtime-api/src/client/identity/http.rs
Labels: needs-sdk-review

#3447 Replace the crates.io API with the sparse index
  tools/ci-build/publisher/Cargo.lock
  tools/ci-build/publisher/Cargo.toml
  tools/ci-build/publisher/src/publish.rs
  tools/ci-build/publisher/src/subcommand/claim_crate_names.rs
  tools/ci-build/publisher/src/subcommand/publish.rs
  tools/ci-build/runtime-versioner/Cargo.lock
  tools/ci-build/runtime-versioner/src/command/audit.rs
  tools/ci-build/runtime-versioner/src/main.rs
  tools/ci-build/sdk-lints/Cargo.lock
  tools/ci-build/smithy-rs-tool-common/Cargo.toml
  tools/ci-build/smithy-rs-tool-common/src/index.rs
  tools/ci-build/smithy-rs-tool-common/src/lib.rs
  tools/ci-build/smithy-rs-tool-common/src/retry.rs
Labels: needs-sdk-review

#3450 Run runtime crate version audit as part of pre-commit
  .pre-commit-config.yaml
  .pre-commit-hooks/runtime-versioner.sh
Labels: needs-sdk-review

#3448 Independently version all runtime crates
  aws/rust-runtime/aws-config/Cargo.toml
  aws/rust-runtime/aws-credential-types/Cargo.toml
  aws/rust-runtime/aws-inlineable/Cargo.toml
  aws/rust-runtime/aws-runtime-api/Cargo.toml
  aws/rust-runtime/aws-runtime/Cargo.toml
  aws/rust-runtime/aws-sigv4/Cargo.toml
  aws/rust-runtime/aws-types/Cargo.toml
  rust-runtime/aws-smithy-async/Cargo.toml
  rust-runtime/aws-smithy-checksums/Cargo.toml
  rust-runtime/aws-smithy-http-server-python/Cargo.toml
  rust-runtime/aws-smithy-http-server-typescript/Cargo.toml
  rust-runtime/aws-smithy-http-server/Cargo.toml
  rust-runtime/aws-smithy-http/Cargo.toml
  rust-runtime/aws-smithy-json/Cargo.toml
  rust-runtime/aws-smithy-protocol-test/Cargo.toml
  rust-runtime/aws-smithy-query/Cargo.toml
  rust-runtime/aws-smithy-runtime-api/Cargo.toml
  rust-runtime/aws-smithy-runtime/Cargo.toml
  rust-runtime/aws-smithy-types-convert/Cargo.toml
  rust-runtime/aws-smithy-types/Cargo.toml
  rust-runtime/aws-smithy-xml/Cargo.toml
  rust-runtime/inlineable/Cargo.toml
Labels: needs-sdk-review
